# Generated by Django 6.0.5 on 2026-06-02 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeCrédit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_demande', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duree_mois', models.PositiveIntegerField(help_text='Durée du crédit en mois')),
                ('motif', models.TextField()),
                ('piece_justif', models.FileField(blank=True, null=True, upload_to='credits/pieces/')),
                ('statut', models.CharField(choices=[('soumise', 'Soumise'), ('en_analyse', 'En analyse'), ('approuvee', 'Approuvée'), ('decaissee', 'Décaissée'), ('rejetee', 'Rejetée')], default='soumise', max_length=20)),
                ('score_eligibilite', models.FloatField(blank=True, null=True)),
                ('montant_approuve', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('taux_interet', models.DecimalField(decimal_places=2, default=12.0, help_text='Taux annuel en %', max_digits=5)),
                ('commentaire_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_traitant', models.ForeignKey(blank=True, limit_choices_to={'role': 'agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_traites', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_credit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de crédit',
                'verbose_name_plural': 'Demandes de crédit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Echeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text="Numéro de l'échéance (1, 2, 3…)")),
                ('date_echeance', models.DateField()),
                ('montant_du', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_capital', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_interet', models.DecimalField(decimal_places=2, max_digits=12)),
                ('est_payee', models.BooleanField(default=False)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='credits.demandecrédit')),
            ],
            options={
                'verbose_name': 'Échéance',
                'verbose_name_plural': 'Échéances',
                'ordering': ['numero'],
            },
        ),
    ]
