# Generated by Django 6.0.5 on 2026-06-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecrédit',
            name='est_soldee',
            field=models.BooleanField(default=False),
        ),
    ]
