# Generated by Django 6.0.5 on 2026-06-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_demandecrédit_est_soldee'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecrédit',
            name='reference_paiement',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
