# Generated by Django 6.0.5 on 2026-06-02 20:20

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitAssurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('type_produit', models.CharField(choices=[('vie', 'Assurance Vie'), ('deces', 'Assurance Décès-Invalidité'), ('credit', 'Assurance Crédit')], max_length=20)),
                ('description', models.TextField()),
                ('prime_mensuelle', models.DecimalField(decimal_places=2, help_text='Montant de la prime mensuelle en FCFA', max_digits=10)),
                ('duree_mois', models.PositiveIntegerField(help_text='Durée de couverture en mois')),
                ('montant_couverture', models.DecimalField(decimal_places=2, help_text='Capital assuré en FCFA', max_digits=14)),
                ('est_actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Produit d'assurance",
                'verbose_name_plural': "Produits d'assurance",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Souscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('active', 'Active'), ('expiree', 'Expirée'), ('resiliee', 'Résiliée')], default='active', max_length=15)),
                ('date_debut', models.DateField(default=datetime.date.today)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('reference_paiement', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='souscriptions', to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='souscriptions', to='insurance.produitassurance')),
            ],
            options={
                'verbose_name': 'Souscription',
                'verbose_name_plural': 'Souscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
