# Generated by Django 6.0.5 on 2026-06-22 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='souscription',
            name='agent_traitant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='souscriptions_traitees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='souscription',
            name='motif_rejet',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='souscription',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('en_cours', 'En cours'), ('rejetee', 'Rejetée'), ('expiree', 'Expirée'), ('resiliee', 'Résiliée')], default='en_attente', max_length=15),
        ),
    ]
