# Generated by Django 6.0.5 on 2026-06-22 23:58

from django.db import migrations


def active_vers_en_cours(apps, schema_editor):
    """Les souscriptions « active » deviennent « en_cours » (déjà validées)."""
    Souscription = apps.get_model('insurance', 'Souscription')
    Souscription.objects.filter(statut='active').update(statut='en_cours')


def en_cours_vers_active(apps, schema_editor):
    Souscription = apps.get_model('insurance', 'Souscription')
    Souscription.objects.filter(statut='en_cours').update(statut='active')


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_souscription_agent_traitant_souscription_motif_rejet_and_more'),
    ]

    operations = [
        migrations.RunPython(active_vers_en_cours, en_cours_vers_active),
    ]
