# Generated by Django 6.0.5 on 2026-06-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_conversion_statut_active_en_cours'),
    ]

    operations = [
        migrations.AddField(
            model_name='souscription',
            name='resiliation_demandee',
            field=models.BooleanField(default=False),
        ),
    ]
