# Generated by Django 6.0.5 on 2026-06-22 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80, unique=True)),
                ('couleur', models.CharField(default='#F2640D', help_text='Couleur du badge (hex).', max_length=20)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='demande_credit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='credits.demandecrédit'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='sujet',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='message',
            name='est_recu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='piece_jointe',
            field=models.FileField(blank=True, null=True, upload_to='chat/pieces/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('resolue', 'Résolue'), ('fermee', 'Fermée')], default='en_attente', max_length=15),
        ),
        migrations.AlterField(
            model_name='message',
            name='contenu',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='conversations', to='chat.categorie'),
        ),
        migrations.CreateModel(
            name='EvaluationConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField()),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='chat.conversation')),
            ],
            options={
                'verbose_name': 'Évaluation de conversation',
                'verbose_name_plural': 'Évaluations de conversation',
            },
        ),
    ]
