# Generated by Django 6.0.5 on 2026-06-22 19:44

from django.db import migrations


# Catégories par défaut (nom, couleur) pour le support / tickets.
CATEGORIES_DEFAUT = [
    ("Demande de crédit", "#F2640D"),
    ("Paiement",          "#0B9C66"),
    ("Assurance",         "#3B82F6"),
    ("Priorité haute",    "#DC2626"),
    ("Question générale", "#726B7E"),
]


def creer_categories(apps, schema_editor):
    Categorie = apps.get_model('chat', 'Categorie')
    for nom, couleur in CATEGORIES_DEFAUT:
        Categorie.objects.get_or_create(nom=nom, defaults={'couleur': couleur})


def supprimer_categories(apps, schema_editor):
    Categorie = apps.get_model('chat', 'Categorie')
    Categorie.objects.filter(nom__in=[c[0] for c in CATEGORIES_DEFAUT]).delete()


def convertir_statuts(apps, schema_editor):
    """L'ancien statut « ouverte » devient « en_cours »."""
    Conversation = apps.get_model('chat', 'Conversation')
    Conversation.objects.filter(statut='ouverte').update(statut='en_cours')


def restaurer_statuts(apps, schema_editor):
    Conversation = apps.get_model('chat', 'Conversation')
    Conversation.objects.filter(statut='en_cours').update(statut='ouverte')


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_categorie_conversation_demande_credit_and_more'),
    ]

    operations = [
        migrations.RunPython(creer_categories, supprimer_categories),
        migrations.RunPython(convertir_statuts, restaurer_statuts),
    ]
