# Generated by Django 6.0.5 on 2026-06-22 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_seed_categories_et_conversion_statuts'),
        ('insurance', '0002_souscription_agent_traitant_souscription_motif_rejet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='souscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='insurance.souscription'),
        ),
    ]
