# Generated by Django 6.0.5 on 2026-06-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='est_disponible',
            field=models.BooleanField(default=False, help_text="Disponibilité de l'agent pour le support client"),
        ),
    ]
