# Generated by Django 6.0.5 on 2026-06-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otptoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialite',
            field=models.CharField(blank=True, choices=[('general', 'Généraliste'), ('credit', 'Crédit'), ('assurance', 'Assurance'), ('recouvrement', 'Recouvrement')], help_text="Spécialité de l'agent (support client).", max_length=20),
        ),
    ]
