# Generated by Django 6.0.5 on 2026-06-02 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode_paiement', models.CharField(choices=[('orange_money', 'Orange Money'), ('wave', 'Wave'), ('mtn_momo', 'MTN MoMo'), ('especes', 'Espèces')], default='especes', max_length=20)),
                ('reference_transaction', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_enregistres', to=settings.AUTH_USER_MODEL)),
                ('echeance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='credits.echeance')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='Penalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taux_penalite', models.DecimalField(decimal_places=2, default=2.0, help_text='Taux mensuel de pénalité en %', max_digits=5)),
                ('jours_retard', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('echeance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='penalite', to='credits.echeance')),
            ],
            options={
                'verbose_name': 'Pénalité',
                'verbose_name_plural': 'Pénalités',
            },
        ),
    ]
