# Generated by Django 6.0.5 on 2026-06-23 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repayments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé')], default='valide', max_length=12),
        ),
        migrations.AddField(
            model_name='paiement',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_valides', to=settings.AUTH_USER_MODEL),
        ),
    ]
