# Generated by Django 6.0.5 on 2026-06-02 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notif', models.CharField(choices=[('statut_credit', 'Changement de statut crédit'), ('rappel_echeance', "Rappel d'échéance"), ('retard_echeance', 'Échéance en retard'), ('paiement_recu', 'Paiement reçu'), ('expiration_assurance', 'Expiration assurance'), ('souscription_confirmee', 'Souscription confirmée'), ('message_chat', 'Nouveau message'), ('general', 'Général')], default='general', max_length=30)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('objet_id', models.PositiveIntegerField(blank=True, null=True)),
                ('est_lue', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
